# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  # there is no trigger for "merge to main"
  #push:
  #  branches: [ "ma_in" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number. (e.x.: 2024-02-04)'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get repo 
        uses: actions/checkout@v4

      - name: ZIP certificates
        run: |
          cd $GITHUB_WORKSPACE
          zip -r releasebuild.zip roots intermediaries

      # Runs a set of commands using the runners shell
      - name: Create P7B certificate bundle
        run: |
          cd $GITHUB_WORKSPACE
          certFiles=();for file in $(find ~+ -iname "*.cer");  do echo ${file}; certFiles+=(-certfile ${file}); done;
          openssl crl2pkcs7 -nocrl "${certFiles[@]}" -outform DER -out releasebuild.p7b

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            - **.cer     

      - name: Create release description
        env:
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          DELETED_FILES: ${{ steps.changed-files-specific.outputs.deleted_files }}
        run: |
          cd $GITHUB_WORKSPACE
          
          echo "# Added certificates:" >> ReleaseNotes.md
          if [[ -z "${ADDED_FILES}" ]]
          then
            echo "No certificates added in this release." >> ReleaseNotes.md
          else
            for file in ${ADDED_FILES}; do
              echo "- $file  " >> ReleaseNotes.md
            done
          fi

          echo "# Deleted certificates:" >> ReleaseNotes.md
          if [[ -z "${ADDED_FILES}" ]]
          then
            echo "No certificates deleted in this release." >> ReleaseNotes.md
          else
            for file in ${DELETED_FILES}; do
              echo "- $file  " >> ReleaseNotes.md
            done
          fi

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ inputs.version }}
          artifacts: "releasebuild.zip"
          bodyFile: "ReleaseNotes.md"
